version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: collector
      POSTGRES_PASSWORD: passtest
      POSTGRES_DB: scrapings
    ports:
      - "5632:5432"